apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inline-inputs-prd
  namespace: argocd
spec:
  destination:
    namespace: inline-inputs
    name: minikube
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.9.0
    helm:
      values: |
        podLabels:
          eso: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true