apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-chart-demo-dev
  namespace: argocd
spec:
  destination:
    namespace: umbrella-chart-demo
    name: in-cluster
  project: default
  source:
    path: umbrella-chart-demo
    repoURL: https://github.com/leansangi/k8s-argocd-helm-demo
    targetRevision: HEAD
    helm:
      # https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#values-files
      valueFiles:
      - values-dev.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true