apiVersion: v2
name: umbrella
description: An Umbrella Helm chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: wordpress
    version: 5.0.2
    repository: https://charts.helm.sh/stable