apiVersion: v2
name: umbrella-demo
description: An Umbrella Helm chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- condition: enablePrometheusStack
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 47.2.0