apiVersion: v2
name: umbrella-demo
description: An Umbrella Helm chart
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: helm-guestbook
  version: HEAD
  repository: https://github.com/argoproj/argocd-example-apps